//! Transition guard for the event-log projection (#212).
//!
//! Single chokepoint answering one question: *is this lifecycle event legal
//! given the currently projected run state?* Every emitter of node-lifecycle
//! events (`node_done`, `mark_node_done`, `resume_run` re-evaluation,
//! `restart_node`, the stale detector, the scheduler spawn paths) must consult
//! this guard **before** appending — an illegal transition is rejected before
//! the append, never compensated after.
//!
//! Pure module: no IO, no clock, no DB. Testable in isolation against a
//! projected [`RunState`].

use crate::event_log::{Event, EventKind, NodeStatus, RunState, RunStatus};

/// Outcome of validating a lifecycle event against the projected state.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum Verdict {
    /// The transition is legal: append it.
    Allow,
    /// The transition is a legal duplicate (e.g. a second completion of an
    /// already-completed iteration): skip the append AND any downstream
    /// re-evaluation, but do not surface an error.
    NoOp { reason: String },
    /// The transition is illegal: refuse the append and surface the reason to
    /// the caller (fail-fast, never silent). The `reason` is a **typed cause**
    /// (#515) — one variant per tested condition — not a prose string; its
    /// pre-#515 prose is regenerated byte-for-byte by [`RejectReason`]'s
    /// `Display`, so nothing wire-visible moves.
    Reject { reason: RejectReason },
}

impl Verdict {
    fn noop(reason: impl Into<String>) -> Self {
        Verdict::NoOp {
            reason: reason.into(),
        }
    }

    fn reject(reason: RejectReason) -> Self {
        Verdict::Reject { reason }
    }
}

/// Why the transition guard refused a lifecycle event — **one variant per tested
/// condition**, never per narration (#515). The pre-#515 prose is regenerated by
/// `Display`, byte-for-byte, so nothing wire-visible moves (`completion_rejected`
/// / `restart_refused` keep their slug and their `message`). The discriminant is
/// merely *made available* for a future consumer (#487) to discriminate cleanly;
/// #515 splits no slug itself.
///
/// - The four "event without node_id" sites fold into `MissingNodeId`: the
///   predicate is identical (`event.node_id.is_none()`), only the `EventKind`
///   differs — and unlike `KillReason` the prose is regular, derived from the
///   kind.
/// - The two "run not live" refusals fold into `RunNotLive`: both test
///   `!run_accepts_lifecycle(status)`; "complete" vs "schedule" is narrative,
///   and `kind` selects the historical template. `node_id`/`iter` serve the
///   completion template only.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum RejectReason {
    /// Lifecycle event with no `node_id`. (construction sites 1, 5, 9, 10)
    MissingNodeId { kind: EventKind },
    /// The Run does not accept lifecycle events (not `Running`/`AwaitingUser`).
    /// Covers both completion and start; `node_id`/`iter` feed the completion
    /// template only, and `kind` picks the template. (sites 2, 6)
    RunNotLive {
        run_id: String,
        status: RunStatus,
        node_id: String,
        iter: i64,
        kind: EventKind,
    },
    /// Start refused: a **different** iteration holds the live slot, outside an
    /// open collection lap. The guard tests `live_iter != iter`, so `live_iter`
    /// may be **older** than `iter` — hence NOT `newer_iteration_live` (the
    /// ADR-0037 trap). (site 7)
    ConcurrentIterationLive {
        node_id: String,
        live_iter: i64,
        iter: i64,
    },
    /// Start refused: the iteration is already `Completed` (never redo it).
    /// (site 8)
    IterationAlreadyCompleted { node_id: String, iter: i64 },
    /// Completion refused: the iteration exists but sits in a status one cannot
    /// complete from (`Stopped`/`Stale`/…). (site 3)
    IterationNotCompletable {
        node_id: String,
        iter: i64,
        status: NodeStatus,
    },
    /// Completion refused: no iteration ever started. (site 4)
    IterationNeverStarted { node_id: String, iter: i64 },
}

impl std::fmt::Display for RejectReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RejectReason::MissingNodeId { kind } => {
                let verb = match kind {
                    EventKind::NodeCompleted | EventKind::NodeAutoCompleted => "completion",
                    EventKind::NodeStarted | EventKind::NodeWaiting => "start",
                    EventKind::NodeFailed => "fail",
                    EventKind::NodeInterrupted => "interrupt",
                    EventKind::NodeStale => "stale",
                    // The guard only builds MissingNodeId for the six kinds
                    // above; defensive.
                    _ => "lifecycle",
                };
                write!(f, "{verb} event without node_id")
            }
            RejectReason::RunNotLive {
                run_id,
                status,
                node_id,
                iter,
                kind,
            } => match kind {
                EventKind::NodeCompleted | EventKind::NodeAutoCompleted => write!(
                    f,
                    "run {run_id} is {status:?}: cannot complete node {node_id} iter {iter} — resume the run first"
                ),
                _ => write!(
                    f,
                    "run {run_id} is {status:?}: no scheduling on a non-running run — resume the run first"
                ),
            },
            RejectReason::ConcurrentIterationLive {
                node_id,
                live_iter,
                iter,
            } => write!(
                f,
                "node {node_id} iter {live_iter} is still live: refusing concurrent iter {iter}"
            ),
            RejectReason::IterationAlreadyCompleted { node_id, iter } => write!(
                f,
                "node {node_id} iter {iter} already completed: refusing to re-run it"
            ),
            RejectReason::IterationNotCompletable {
                node_id,
                iter,
                status,
            } => write!(f, "node {node_id} iter {iter} is {status:?}: cannot complete"),
            RejectReason::IterationNeverStarted { node_id, iter } => write!(
                f,
                "node {node_id} iter {iter} was never started (no node_started event): cannot complete"
            ),
        }
    }
}

fn run_accepts_lifecycle(status: &RunStatus) -> bool {
    matches!(status, RunStatus::Running | RunStatus::AwaitingUser)
}

fn iteration_status(state: &RunState, node_id: &str, iter: i64) -> Option<NodeStatus> {
    state
        .nodes
        .get(node_id)
        .and_then(|n| n.iterations.iter().find(|i| i.iter == iter))
        .map(|i| i.status.clone())
}

/// The iteration currently holding (or owed) a live agent session for this
/// node, if any: `Running` or `AwaitingUser` iteration rows, or the node-level
/// `Waiting` marker (throttled, no iteration row yet — #159).
fn live_iteration(state: &RunState, node_id: &str) -> Option<i64> {
    let node = state.nodes.get(node_id)?;
    if node.status == NodeStatus::Waiting {
        return Some(node.iter);
    }
    node.iterations
        .iter()
        .filter(|i| matches!(i.status, NodeStatus::Running | NodeStatus::AwaitingUser))
        .map(|i| i.iter)
        .max()
}

/// Validate a lifecycle event against the projected run state.
///
/// Non-lifecycle kinds are always allowed: the guard governs node lifecycle
/// transitions (`NodeStarted`, `NodeWaiting`, `NodeCompleted`,
/// `NodeAutoCompleted`, `NodeStale`), not control-flow bookkeeping.
pub(crate) fn validate_transition(state: Option<&RunState>, event: &Event) -> Verdict {
    let Some(state) = state else {
        // No projected state yet (run not started): nothing to validate
        // against. The first RunStarted event creates the state.
        return Verdict::Allow;
    };

    match event.kind {
        EventKind::NodeCompleted | EventKind::NodeAutoCompleted => {
            validate_completion(state, event)
        }
        EventKind::NodeStarted | EventKind::NodeWaiting => validate_start(state, event),
        EventKind::NodeStale => validate_stale(state, event),
        EventKind::NodeFailed => validate_fail(state, event),
        EventKind::NodeInterrupted => validate_interrupt(state, event),
        _ => Verdict::Allow,
    }
}

/// Is `(node_id, iter)` a **parallel item lap** of a collection region whose
/// barrier is still open (#453)?
///
/// The single, narrow exemption to "a node has at most one live iteration".
/// ADR-0011 / ADR-0026 specify a `kind: collection` region as a *parallel*
/// fan-out of the same node — `Spawn { entry, iter: 1..=total }` in one burst —
/// while the guard (#212) exists to stop exactly that shape everywhere else.
/// The two invariants met head-on at the spawn seam: laps ≥ 2 were rejected
/// deterministically 1 ms after lap 1 started, the barrier never fired, and the
/// Run wedged `running` with no live session and nothing to re-drive it.
///
/// Scoped as tightly as the semantics allow, so #212's chokepoint keeps holding
/// for `restart_node`, the liveness sweep and boot recovery:
/// - the region must exist in the projection and still be **open** (`!done`) —
///   once the barrier fires the node is a plain node again;
/// - `node_id` must be one the region **governs** (its entry or a member);
/// - `iter` must be a real lap index, `1..=total_items` — an out-of-range
///   iteration is not an item and stays refused.
///
/// Says nothing about *completed* laps: re-running a finished lap is refused by
/// the caller as it always was.
fn is_open_collection_lap(state: &RunState, node_id: &str, iter: i64) -> bool {
    state
        .collection_states
        .values()
        .any(|cs| !cs.done && iter >= 1 && iter <= cs.total_items && cs.governs(node_id))
}

/// Scheduler-side dedup for proposed `Spawn { node, iter }` actions on
/// re-evaluation paths (resume_run, extend_cycle, region routes, loop/foreach
/// body completion). A proposal is superfluous when the node already has a
/// live iteration — any iter, *including* the proposed one: a running session
/// must never be doubled by the scheduler (restart_node alone may re-spawn a
/// live iteration) — or when the proposed iteration has already completed.
///
/// Returns the human-readable reason when the proposal should be skipped.
pub(crate) fn spawn_superfluous(state: &RunState, node_id: &str, iter: i64) -> Option<String> {
    if let Some(live_iter) = live_iteration(state, node_id) {
        // #453: a sibling item lap of an open collection region is concurrent
        // work by design, never a redundant proposal. Only a proposal for the
        // live lap ITSELF is superfluous here.
        if !(live_iter != iter && is_open_collection_lap(state, node_id, iter)) {
            return Some(format!(
                "node {node_id} iter {live_iter} is live: scheduler will not spawn iter {iter}"
            ));
        }
    }
    // #620: a `Skipped` iteration is as settled as a `Completed` one — never
    // re-spawn either.
    if matches!(
        iteration_status(state, node_id, iter),
        Some(NodeStatus::Completed) | Some(NodeStatus::Skipped)
    ) {
        return Some(format!(
            "node {node_id} iter {iter} already completed: nothing to spawn"
        ));
    }
    None
}

/// Head-of-handler precondition for a **retry** (`node_retry`, #487).
///
/// `node_retry` must call this as its FIRST gesture — before it stops the node and
/// before its two `invalidate_nodes`. A refusal that lands any later leaves the
/// self-invalidation committed (`NodeInvalidated` is not a lifecycle transition, so
/// the guard never refuses it — `validate_transition`'s `_ => Allow` arm), and once
/// appended the node is gone from the projection with no replacement: the
/// "`pending` forever" freeze the production incident reproduced (#496).
///
/// The predicate is run-liveness **alone** (`run_accepts_lifecycle`), NOT a
/// synthetic `NodeStarted` probe. Retry legitimately re-spawns a `Running` node (it
/// stops it first) and a `Completed` node (it advances to `iter+1`), both of which
/// [`validate_start`] refuses (`ConcurrentIterationLive` / `IterationAlreadyCompleted`).
/// That is the exact trap #489 flagged for #487: the synthetic probe is the right
/// one for `restart_node` (a same-iter re-spawn) and the wrong one here. So this
/// asks only the one question a retry shares with every other spawn — is the Run
/// live? — and lets the handler resolve concurrency itself.
///
/// Returns the typed refusal (whose `Display` is the same "resume the run first"
/// prose the `append_event` backstop emits) when the Run is terminal/paused, else
/// `None`. `iter` is the iteration the retry would spawn (`current + 1`); it feeds
/// the refusal template only, the predicate ignores it.
pub(crate) fn retry_run_precondition(
    state: &RunState,
    node_id: &str,
    iter: i64,
) -> Option<RejectReason> {
    if run_accepts_lifecycle(&state.status) {
        return None;
    }
    Some(RejectReason::RunNotLive {
        run_id: state.run_id.clone(),
        status: state.status.clone(),
        node_id: node_id.to_string(),
        iter,
        kind: EventKind::NodeStarted,
    })
}

fn validate_completion(state: &RunState, event: &Event) -> Verdict {
    let Some(node_id) = event.node_id.as_deref() else {
        return Verdict::reject(RejectReason::MissingNodeId {
            kind: event.kind.clone(),
        });
    };
    let iter = event.iter.unwrap_or(1);

    if !run_accepts_lifecycle(&state.status) {
        return Verdict::reject(RejectReason::RunNotLive {
            run_id: state.run_id.clone(),
            status: state.status.clone(),
            node_id: node_id.to_string(),
            iter,
            kind: event.kind.clone(),
        });
    }

    match iteration_status(state, node_id, iter) {
        // #620: a `Skipped` iter is a settled completion too — a duplicate
        // completion (skip or otherwise) landing on it is a no-op, not a reject.
        Some(NodeStatus::Completed) | Some(NodeStatus::Skipped) => Verdict::noop(format!(
            "node {node_id} iter {iter} is already completed: duplicate completion ignored"
        )),
        Some(NodeStatus::Running) | Some(NodeStatus::AwaitingUser) | Some(NodeStatus::Failed) => {
            Verdict::Allow
        }
        Some(other) => Verdict::reject(RejectReason::IterationNotCompletable {
            node_id: node_id.to_string(),
            iter,
            status: other,
        }),
        None => {
            // #600: a **skip** (`skip_node` / reachability auto-skip) legitimately
            // completes a node that never started — it marks a node stuck waiting
            // on an unreachable input as satisfied so the run does not hang. Any
            // other completion of a never-started iteration stays a reject.
            if is_skip_completion(event) {
                Verdict::Allow
            } else {
                Verdict::reject(RejectReason::IterationNeverStarted {
                    node_id: node_id.to_string(),
                    iter,
                })
            }
        }
    }
}

/// True when a `NodeCompleted` event carries the `skipped: true` marker of a local
/// skip (`skip_node`) or a reachability auto-skip (#600). Such a completion is
/// allowed even for a node that never started.
fn is_skip_completion(event: &Event) -> bool {
    event
        .payload
        .as_ref()
        .and_then(|p| p.get("skipped"))
        .and_then(|v| v.as_bool())
        .unwrap_or(false)
}

fn validate_start(state: &RunState, event: &Event) -> Verdict {
    let Some(node_id) = event.node_id.as_deref() else {
        return Verdict::reject(RejectReason::MissingNodeId {
            kind: event.kind.clone(),
        });
    };
    let iter = event.iter.unwrap_or(1);

    if !run_accepts_lifecycle(&state.status) {
        return Verdict::reject(RejectReason::RunNotLive {
            run_id: state.run_id.clone(),
            status: state.status.clone(),
            node_id: node_id.to_string(),
            iter,
            kind: event.kind.clone(),
        });
    }

    if let Some(live_iter) = live_iteration(state, node_id) {
        // #453: item laps of an open collection region run in parallel — a live
        // sibling lap is the intended shape, not a concurrency violation.
        if live_iter != iter && !is_open_collection_lap(state, node_id, iter) {
            return Verdict::reject(RejectReason::ConcurrentIterationLive {
                node_id: node_id.to_string(),
                live_iter,
                iter,
            });
        }
        // Same iter: legal restart/promotion of the live iteration.
    }

    // #620: refuse a restart of a `Skipped` iter exactly as of a `Completed` one —
    // both are settled and must not be re-spawned.
    if matches!(
        iteration_status(state, node_id, iter),
        Some(NodeStatus::Completed) | Some(NodeStatus::Skipped)
    ) {
        return Verdict::reject(RejectReason::IterationAlreadyCompleted {
            node_id: node_id.to_string(),
            iter,
        });
    }

    Verdict::Allow
}

/// Validate a `NodeFailed` emitted by the liveness sweep or boot recovery
/// (#213). These detectors snapshot the run, decide, then emit — by the time
/// the failure lands the iteration may already have reached a terminal state
/// organically. The guard drops the late failure as a no-op rather than
/// overwriting a completed/failed/stopped/stale iteration, and ignores a
/// failure for an iteration that was never started (nothing live to fail).
/// A failure on a live (`Running`/`AwaitingUser`/`Waiting`) iteration — the
/// reason the detectors exist — is allowed.
fn validate_fail(state: &RunState, event: &Event) -> Verdict {
    let Some(node_id) = event.node_id.as_deref() else {
        return Verdict::reject(RejectReason::MissingNodeId {
            kind: event.kind.clone(),
        });
    };
    let iter = event.iter.unwrap_or(1);

    match iteration_status(state, node_id, iter) {
        Some(NodeStatus::Completed)
        | Some(NodeStatus::Skipped)
        | Some(NodeStatus::Failed)
        | Some(NodeStatus::Stopped)
        | Some(NodeStatus::Stale) => Verdict::noop(format!(
            "node {node_id} iter {iter} is already terminal: failure ignored"
        )),
        None => Verdict::noop(format!(
            "node {node_id} iter {iter} has no started iteration: failure ignored"
        )),
        _ => Verdict::Allow,
    }
}

/// Validate a `NodeInterrupted` — an infra incident on a node (ADR-0049),
/// emitted by the liveness sweep, boot recovery, or a spawn-abort.
///
/// Two differences from [`validate_fail`], both load-bearing:
///
/// 1. A **never-started** iteration is **allowed**, not a no-op: a spawn that
///    aborts *before* `NodeStarted` (ADR-0050 §1 — e.g. a surviving `pdo/sub-*`
///    branch collides on `git worktree add -b`) still names its node, and the
///    projection materialises it `Interrupted` so the run parks visibly. This is
///    the exact case `validate_fail` drops as "never started", which is why the
///    before-start abort had to emit `RunFailed` before résilience.
/// 2. The run-liveness gate is **not** applied: an interrupt lands on a run that
///    is still `Running`, and a race that lets it arrive just after a terminal
///    event should be dropped as a duplicate rather than resurrect the run — the
///    already-terminal iteration arm below covers that.
///
/// A late interrupt for an iteration that reached a terminal state organically
/// (or was already interrupted) is a no-op, never an overwrite.
fn validate_interrupt(state: &RunState, event: &Event) -> Verdict {
    let Some(node_id) = event.node_id.as_deref() else {
        return Verdict::reject(RejectReason::MissingNodeId {
            kind: event.kind.clone(),
        });
    };
    let iter = event.iter.unwrap_or(1);

    match iteration_status(state, node_id, iter) {
        Some(NodeStatus::Completed)
        | Some(NodeStatus::Skipped)
        | Some(NodeStatus::Failed)
        | Some(NodeStatus::Stopped)
        | Some(NodeStatus::Stale)
        | Some(NodeStatus::Interrupted) => Verdict::noop(format!(
            "node {node_id} iter {iter} is already terminal: interrupt ignored"
        )),
        // `None` (never started, or a node materialised by a prior before-start
        // interrupt with no iteration row): a fresh interrupt is allowed unless
        // the node itself is already interrupted — a re-interrupt of the same
        // never-started node is a no-op.
        None if state
            .nodes
            .get(node_id)
            .is_some_and(|n| n.status == NodeStatus::Interrupted) =>
        {
            Verdict::noop(format!(
                "node {node_id} is already interrupted: interrupt ignored"
            ))
        }
        // Running / AwaitingUser / never-started — the incident is allowed.
        _ => Verdict::Allow,
    }
}

fn validate_stale(state: &RunState, event: &Event) -> Verdict {
    let Some(node_id) = event.node_id.as_deref() else {
        return Verdict::reject(RejectReason::MissingNodeId {
            kind: event.kind.clone(),
        });
    };
    let iter = event.iter.unwrap_or(1);

    match iteration_status(state, node_id, iter) {
        Some(NodeStatus::Completed)
        | Some(NodeStatus::Skipped)
        | Some(NodeStatus::Failed)
        | Some(NodeStatus::Stopped)
        | Some(NodeStatus::Stale) => Verdict::noop(format!(
            "node {node_id} iter {iter} is already terminal: stale marker ignored"
        )),
        None => Verdict::noop(format!(
            "node {node_id} iter {iter} has no started iteration: stale marker ignored"
        )),
        _ => Verdict::Allow,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::event_log::{now_iso, project};

    fn ev(kind: EventKind, node_id: Option<&str>, iter: Option<i64>) -> Event {
        let payload = if kind == EventKind::RunStarted {
            Some(serde_json::json!({ "pipeline_name": "test" }))
        } else {
            None
        };
        Event {
            id: None,
            run_id: "run-1".into(),
            ts: now_iso(),
            kind,
            node_id: node_id.map(String::from),
            iter,
            payload,
        }
    }

    fn state_from(events: &[Event]) -> RunState {
        project(events).expect("projected state")
    }

    fn assert_reject(verdict: Verdict, expected_fragment: &str) {
        match verdict {
            Verdict::Reject { reason } => {
                let rendered = reason.to_string();
                assert!(
                    rendered.contains(expected_fragment),
                    "reject reason {rendered:?} should mention {expected_fragment:?}"
                );
            }
            other => panic!("expected Reject, got {other:?}"),
        }
    }

    fn assert_noop(verdict: Verdict) {
        assert!(
            matches!(verdict, Verdict::NoOp { .. }),
            "expected NoOp, got {verdict:?}"
        );
    }

    // --- NodeCompleted ---

    #[test]
    fn duplicate_completion_of_completed_iteration_is_noop() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        );
        assert_noop(verdict);
    }

    #[test]
    fn completion_of_running_iteration_is_allowed() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        );
        assert_eq!(verdict, Verdict::Allow);
    }

    #[test]
    fn completion_of_never_started_iteration_is_rejected() {
        let state = state_from(&[ev(EventKind::RunStarted, None, None)]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeCompleted, Some("ghost"), Some(1)),
        );
        assert_reject(verdict, "never started");
    }

    #[test]
    fn skip_completion_of_never_started_iteration_is_allowed() {
        // #600: a `skip_node` / auto-skip completion carries `skipped: true` and is
        // allowed to satisfy a node that never started (stuck on an unreachable
        // input) — the one exception to "a completion needs a start".
        let state = state_from(&[ev(EventKind::RunStarted, None, None)]);
        let mut skip = ev(EventKind::NodeCompleted, Some("orphan"), Some(1));
        skip.payload = Some(serde_json::json!({ "skipped": true }));
        assert_eq!(validate_transition(Some(&state), &skip), Verdict::Allow);
    }

    #[test]
    fn skip_completion_of_an_already_completed_iteration_still_noops() {
        // The skip exception only relaxes the never-started case; a duplicate skip
        // on an already-satisfied node is still the idempotent no-op.
        let mut done = ev(EventKind::NodeCompleted, Some("orphan"), Some(1));
        done.payload = Some(serde_json::json!({ "skipped": true }));
        let state = state_from(&[ev(EventKind::RunStarted, None, None), done.clone()]);
        assert_noop(validate_transition(Some(&state), &done));
    }

    #[test]
    fn completion_of_unstarted_higher_iteration_is_rejected() {
        // worker ran iter 1 only; completing iter 2 (never started) is illegal.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeCompleted, Some("worker"), Some(2)),
        );
        assert_reject(verdict, "never started");
    }

    #[test]
    fn completion_on_failed_run_is_rejected() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::RunFailed, None, None),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        );
        assert_reject(verdict, "resume the run");
    }

    #[test]
    fn completion_of_failed_iteration_is_allowed() {
        // mark_node_done on a failed node (outputs fixed by hand) is a
        // supported recovery path.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeFailed, Some("worker"), Some(1)),
            // node_fail also fails the run; a resume_run lifts it.
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        );
        assert_eq!(verdict, Verdict::Allow);
    }

    #[test]
    fn auto_completion_follows_completion_rules() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeAutoCompleted, Some("worker"), Some(1)),
        );
        assert_noop(verdict);
    }

    // --- NodeStarted ---

    #[test]
    fn start_while_another_iteration_is_live_is_rejected() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(2)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("worker"), Some(3)),
        );
        assert_reject(verdict, "still live");
    }

    #[test]
    fn restart_of_the_live_iteration_is_allowed() {
        // restart_node kills the session and re-spawns the SAME iter.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(2)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("worker"), Some(2)),
        );
        assert_eq!(verdict, Verdict::Allow);
    }

    #[test]
    fn restart_of_older_iter_while_newer_is_live_is_rejected() {
        // #196: restart_node iter 1 raced the scheduler's iter-2 spawn.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("griller"), Some(1)),
            ev(EventKind::NodeCompleted, Some("griller"), Some(1)),
            ev(EventKind::NodeStarted, Some("griller"), Some(2)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("griller"), Some(1)),
        );
        assert_reject(verdict, "still live");
    }

    #[test]
    fn start_of_already_completed_iteration_is_rejected() {
        // #195/#198: never redo completed work.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        );
        assert_reject(verdict, "already completed");
    }

    #[test]
    fn start_on_failed_run_is_rejected() {
        // #197: a failed run schedules nothing until resume_run.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::RunFailed, None, None),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        );
        assert_reject(verdict, "non-running run");
    }

    #[test]
    fn start_on_completed_run_is_rejected() {
        // #221: once a run reaches RunCompleted it is terminal. A re-evaluation
        // path (e.g. resume_run on a finished run) must not re-spawn an already
        // satisfied node/loop — the guard rejects scheduling on a non-running
        // run. This is the backstop that keeps the projection fix honest even if
        // some path tries to schedule against a completed run.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
            ev(EventKind::RunCompleted, None, None),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("worker"), Some(2)),
        );
        assert_reject(verdict, "non-running run");
    }

    #[test]
    fn completion_on_completed_run_is_rejected() {
        // Symmetric to the start case: no node lifecycle on a terminal run.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
            ev(EventKind::RunCompleted, None, None),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        );
        assert_reject(verdict, "resume the run");
    }

    #[test]
    fn start_of_fresh_node_is_allowed() {
        let state = state_from(&[ev(EventKind::RunStarted, None, None)]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        );
        assert_eq!(verdict, Verdict::Allow);
    }

    #[test]
    fn start_of_next_iter_after_completed_iter_is_allowed() {
        // Lap advance: iter 1 completed, nothing live, iter 2 may start.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("worker"), Some(2)),
        );
        assert_eq!(verdict, Verdict::Allow);
    }

    #[test]
    fn promotion_of_waiting_node_at_same_iter_is_allowed() {
        // #159 throttling: NodeWaiting then NodeStarted at the same iter.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeWaiting, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        );
        assert_eq!(verdict, Verdict::Allow);
    }

    #[test]
    fn start_of_other_iter_while_node_is_waiting_is_rejected() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeWaiting, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("worker"), Some(2)),
        );
        assert_reject(verdict, "still live");
    }

    #[test]
    fn restart_of_failed_iteration_is_allowed() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeFailed, Some("worker"), Some(1)),
            // resume_run lifted the run-level failure.
            ev(EventKind::RunResumed, None, None),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        );
        assert_eq!(verdict, Verdict::Allow);
    }

    // --- NodeStale ---

    #[test]
    fn stale_on_completed_iteration_is_noop() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStale, Some("worker"), Some(1)),
        );
        assert_noop(verdict);
    }

    #[test]
    fn stale_on_running_iteration_is_allowed() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeStale, Some("worker"), Some(1)),
        );
        assert_eq!(verdict, Verdict::Allow);
    }

    // --- NodeFailed (detection / recovery, #213) ---

    #[test]
    fn fail_on_completed_iteration_is_noop() {
        // The liveness sweep / boot recovery snapshots the run, then emits a
        // failure. If the node completed organically in between, the guard must
        // drop the late failure as a no-op — never overwrite a completed node.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeFailed, Some("worker"), Some(1)),
        );
        assert_noop(verdict);
    }

    #[test]
    fn fail_on_running_iteration_is_allowed() {
        // The liveness sweep marking a Running node Failed (dead session) is
        // exactly the transition #213 exists to allow.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        ]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeFailed, Some("worker"), Some(1)),
        );
        assert_eq!(verdict, Verdict::Allow);
    }

    #[test]
    fn fail_on_never_started_iteration_is_noop() {
        let state = state_from(&[ev(EventKind::RunStarted, None, None)]);
        let verdict = validate_transition(
            Some(&state),
            &ev(EventKind::NodeFailed, Some("ghost"), Some(1)),
        );
        assert_noop(verdict);
    }

    // --- NodeInterrupted (ADR-0049/0050) --------------------------------------

    #[test]
    fn interrupt_on_running_iteration_is_allowed() {
        // Session death / after-start spawn abort on a live iteration.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        ]);
        assert_eq!(
            validate_transition(
                Some(&state),
                &ev(EventKind::NodeInterrupted, Some("worker"), Some(1))
            ),
            Verdict::Allow
        );
    }

    #[test]
    fn interrupt_on_never_started_iteration_is_allowed() {
        // ADR-0050 §1: a spawn abort BEFORE NodeStarted must still name its node —
        // unlike NodeFailed, the guard ALLOWS it so the projection can materialise
        // the interrupted node and park the run visibly.
        let state = state_from(&[ev(EventKind::RunStarted, None, None)]);
        assert_eq!(
            validate_transition(
                Some(&state),
                &ev(EventKind::NodeInterrupted, Some("ghost"), Some(1))
            ),
            Verdict::Allow
        );
    }

    #[test]
    fn interrupt_on_completed_iteration_is_noop() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        ]);
        assert_noop(validate_transition(
            Some(&state),
            &ev(EventKind::NodeInterrupted, Some("worker"), Some(1)),
        ));
    }

    // --- spawn_superfluous (scheduler-side dedup) ---

    #[test]
    fn spawn_proposal_for_running_node_is_superfluous_at_any_iter() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("b"), Some(1)),
        ]);
        // Same iter: the running session must not be doubled by the scheduler.
        assert!(spawn_superfluous(&state, "b", 1).is_some());
        // Next iter: #201 — no concurrent second iteration.
        assert!(spawn_superfluous(&state, "b", 2).is_some());
    }

    #[test]
    fn spawn_proposal_for_completed_iteration_is_superfluous() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("b"), Some(1)),
            ev(EventKind::NodeCompleted, Some("b"), Some(1)),
        ]);
        assert!(spawn_superfluous(&state, "b", 1).is_some());
        // A fresh lap at iter 2 is legitimate (extend_cycle / region laps).
        assert!(spawn_superfluous(&state, "b", 2).is_none());
    }

    #[test]
    fn spawn_proposal_for_fresh_or_failed_node_is_not_superfluous() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("f"), Some(1)),
            ev(EventKind::NodeFailed, Some("f"), Some(1)),
            ev(EventKind::RunResumed, None, None),
        ]);
        assert!(spawn_superfluous(&state, "never-ran", 1).is_none());
        assert!(spawn_superfluous(&state, "f", 1).is_none());
    }

    #[test]
    fn spawn_proposal_for_waiting_node_is_superfluous() {
        // A throttled node is owned by retry_waiting_nodes; re-evaluation
        // paths must not double-schedule it.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeWaiting, Some("w"), Some(1)),
        ]);
        assert!(spawn_superfluous(&state, "w", 1).is_some());
    }

    // --- collection item laps (#453) ---

    /// `collection_started` for a single-member region over `total` items.
    fn collection_started(total: i64) -> Event {
        let mut e = ev(EventKind::CollectionStarted, None, None);
        e.payload = Some(serde_json::json!({
            "region_id": "fan",
            "entry": "worker",
            "members": ["worker"],
            "total_items": total,
        }));
        e
    }

    #[test]
    fn sibling_item_laps_of_an_open_collection_region_may_run_concurrently() {
        // ADR-0011 / ADR-0026: `Spawn { entry, iter: 1..=total }` in one burst.
        // The #212 refusal is what wedged the fan-out at lap 1 (#453).
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            collection_started(3),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        ]);
        for iter in [2, 3] {
            assert_eq!(
                validate_transition(
                    Some(&state),
                    &ev(EventKind::NodeStarted, Some("worker"), Some(iter))
                ),
                Verdict::Allow,
                "lap {iter} of a 3-item region must start alongside lap 1"
            );
        }
    }

    #[test]
    fn a_completed_item_lap_is_never_re_run() {
        // The exemption covers concurrency, not resurrection: #195/#198 still hold
        // inside a region.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            collection_started(2),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
            ev(EventKind::NodeStarted, Some("worker"), Some(2)),
        ]);
        assert_reject(
            validate_transition(
                Some(&state),
                &ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ),
            "already completed",
        );
    }

    #[test]
    fn a_node_outside_the_region_keeps_the_concurrency_refusal() {
        // The narrowness proof #212's other callers (restart_node, the liveness
        // sweep, boot recovery) depend on: an open region in the run exempts ITS
        // members and nobody else.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            collection_started(3),
            ev(EventKind::NodeStarted, Some("outsider"), Some(1)),
        ]);
        assert_reject(
            validate_transition(
                Some(&state),
                &ev(EventKind::NodeStarted, Some("outsider"), Some(2)),
            ),
            "still live",
        );
    }

    #[test]
    fn spawn_proposal_for_a_sibling_item_lap_is_not_superfluous() {
        // The re-evaluation paths (`resume_run`, `extend_cycle`, region routes)
        // must be able to propose a lap the fan-out has not started yet, even
        // while a sibling lap holds a session.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            collection_started(2),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        ]);
        assert!(spawn_superfluous(&state, "worker", 2).is_none());
        // Re-proposing the LIVE lap itself is still superfluous — never double a
        // running session.
        assert!(spawn_superfluous(&state, "worker", 1).is_some());
        // And an out-of-range iteration is not a lap.
        assert!(spawn_superfluous(&state, "worker", 3).is_some());
    }

    // --- retry_run_precondition (#487) ---

    #[test]
    fn retry_precondition_refuses_a_terminal_run_with_resume_prose() {
        // The production incident (#496): Play on a node of a Failed run. The
        // predicate must refuse, and the prose must be the guard's own
        // "resume the run first" (ADR-0035 body reuses it verbatim).
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::RunFailed, None, None),
        ]);
        let reason =
            retry_run_precondition(&state, "worker", 2).expect("a Failed run must refuse a retry");
        assert!(matches!(reason, RejectReason::RunNotLive { .. }));
        assert!(reason.to_string().contains("resume the run first"));
    }

    #[test]
    fn retry_precondition_allows_a_running_node_on_a_live_run() {
        // The non-regression the synthetic-`NodeStarted` probe would break: a
        // still-`Running` node on a live Run. The predicate is run-liveness alone,
        // so it says nothing about the live iteration — the handler stops it first.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
        ]);
        assert!(retry_run_precondition(&state, "worker", 2).is_none());
    }

    #[test]
    fn retry_precondition_allows_a_completed_node_on_a_live_run() {
        // The other case a synthetic probe would break: retrying a `Completed` node
        // (the canvas offers it) advances to `iter+1`; run-liveness alone allows it.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        ]);
        assert!(retry_run_precondition(&state, "worker", 2).is_none());
    }

    #[test]
    fn retry_precondition_refuses_a_paused_run() {
        // `run_accepts_lifecycle` admits only Running/AwaitingUser, so a Paused run
        // is refused too — "resume the run first", not an implicit resume (ADR-0009).
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::RunPaused, None, None),
        ]);
        assert!(retry_run_precondition(&state, "worker", 2).is_some());
    }

    // --- non-lifecycle kinds and missing state ---

    #[test]
    fn non_lifecycle_kinds_are_always_allowed() {
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::RunFailed, None, None),
        ]);
        for kind in [
            EventKind::CommandIssued,
            EventKind::RunResumed,
            EventKind::NodeStopped,
            EventKind::RunCompleted,
        ] {
            let verdict = validate_transition(Some(&state), &ev(kind, Some("worker"), Some(1)));
            assert_eq!(verdict, Verdict::Allow);
        }
    }

    #[test]
    fn missing_state_is_allowed() {
        let verdict =
            validate_transition(None, &ev(EventKind::NodeStarted, Some("worker"), Some(1)));
        assert_eq!(verdict, Verdict::Allow);
    }

    // --- #515: typed reject cause ---

    #[test]
    fn each_refusal_carries_its_typed_reject_reason() {
        // One assertion per `RejectReason` variant, driven through the real
        // guard: a future edit that keeps the prose but swaps the variant fails
        // here even though `assert_reject`'s fragment check would still pass.

        // ConcurrentIterationLive (site 7): a live sibling iteration.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(2)),
        ]);
        assert!(matches!(
            validate_transition(
                Some(&state),
                &ev(EventKind::NodeStarted, Some("worker"), Some(3))
            ),
            Verdict::Reject {
                reason: RejectReason::ConcurrentIterationLive {
                    live_iter: 2,
                    iter: 3,
                    ..
                }
            }
        ));

        // RunNotLive on a start (site 6): the run is Failed.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::RunFailed, None, None),
        ]);
        assert!(matches!(
            validate_transition(
                Some(&state),
                &ev(EventKind::NodeStarted, Some("worker"), Some(1))
            ),
            Verdict::Reject {
                reason: RejectReason::RunNotLive {
                    kind: EventKind::NodeStarted,
                    ..
                }
            }
        ));

        // RunNotLive on a completion (site 2): the run is Failed.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::RunFailed, None, None),
        ]);
        assert!(matches!(
            validate_transition(
                Some(&state),
                &ev(EventKind::NodeCompleted, Some("worker"), Some(1))
            ),
            Verdict::Reject {
                reason: RejectReason::RunNotLive {
                    kind: EventKind::NodeCompleted,
                    ..
                }
            }
        ));

        // IterationAlreadyCompleted (site 8).
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeCompleted, Some("worker"), Some(1)),
        ]);
        assert!(matches!(
            validate_transition(
                Some(&state),
                &ev(EventKind::NodeStarted, Some("worker"), Some(1))
            ),
            Verdict::Reject {
                reason: RejectReason::IterationAlreadyCompleted { .. }
            }
        ));

        // IterationNotCompletable (site 3): a Stopped iteration, run still live.
        let state = state_from(&[
            ev(EventKind::RunStarted, None, None),
            ev(EventKind::NodeStarted, Some("worker"), Some(1)),
            ev(EventKind::NodeStopped, Some("worker"), Some(1)),
        ]);
        assert!(matches!(
            validate_transition(
                Some(&state),
                &ev(EventKind::NodeCompleted, Some("worker"), Some(1))
            ),
            Verdict::Reject {
                reason: RejectReason::IterationNotCompletable {
                    status: NodeStatus::Stopped,
                    ..
                }
            }
        ));

        // IterationNeverStarted (site 4).
        let state = state_from(&[ev(EventKind::RunStarted, None, None)]);
        assert!(matches!(
            validate_transition(
                Some(&state),
                &ev(EventKind::NodeCompleted, Some("ghost"), Some(1))
            ),
            Verdict::Reject {
                reason: RejectReason::IterationNeverStarted { .. }
            }
        ));

        // MissingNodeId (sites 1/5/9/10): a lifecycle event with no node_id.
        let state = state_from(&[ev(EventKind::RunStarted, None, None)]);
        assert!(matches!(
            validate_transition(Some(&state), &ev(EventKind::NodeStarted, None, Some(1))),
            Verdict::Reject {
                reason: RejectReason::MissingNodeId {
                    kind: EventKind::NodeStarted
                }
            }
        ));
    }

    /// One sample per `RejectReason` variant, produced behind a **wildcard-free
    /// `match`** — the `every_refusal()`/`every_restart_verdict()` guard-rail
    /// (#490): adding a variant to `RejectReason` without sampling it here stops
    /// compiling.
    fn every_reject_reason() -> Vec<RejectReason> {
        let all = vec![
            RejectReason::MissingNodeId {
                kind: EventKind::NodeCompleted,
            },
            RejectReason::RunNotLive {
                run_id: "run-1".into(),
                status: RunStatus::Failed,
                node_id: "worker".into(),
                iter: 1,
                kind: EventKind::NodeCompleted,
            },
            RejectReason::ConcurrentIterationLive {
                node_id: "worker".into(),
                live_iter: 2,
                iter: 3,
            },
            RejectReason::IterationAlreadyCompleted {
                node_id: "worker".into(),
                iter: 1,
            },
            RejectReason::IterationNotCompletable {
                node_id: "worker".into(),
                iter: 1,
                status: NodeStatus::Stopped,
            },
            RejectReason::IterationNeverStarted {
                node_id: "worker".into(),
                iter: 1,
            },
        ];

        // Coverage floor: the wildcard-free `match` forces each variant to be
        // named, and the count forces the sample to actually exist.
        let mut seen = std::collections::BTreeSet::new();
        for r in &all {
            let key = match r {
                RejectReason::MissingNodeId { .. } => "MissingNodeId",
                RejectReason::RunNotLive { .. } => "RunNotLive",
                RejectReason::ConcurrentIterationLive { .. } => "ConcurrentIterationLive",
                RejectReason::IterationAlreadyCompleted { .. } => "IterationAlreadyCompleted",
                RejectReason::IterationNotCompletable { .. } => "IterationNotCompletable",
                RejectReason::IterationNeverStarted { .. } => "IterationNeverStarted",
            };
            seen.insert(key);
        }
        assert_eq!(
            seen.len(),
            all.len(),
            "every_reject_reason() must hold exactly one sample per variant"
        );
        all
    }

    #[test]
    fn every_reject_reason_display_is_byte_identical_to_pre_515_prose() {
        // The wire-neutrality guarantee: `Display` reproduces the exact strings
        // the ten construction sites emitted before #515. An em-dash flipped to
        // a hyphen, a lost `{:?}`, a reordered clause — each fails here.
        let cases: Vec<(RejectReason, &str)> = vec![
            (
                RejectReason::ConcurrentIterationLive {
                    node_id: "worker".into(),
                    live_iter: 2,
                    iter: 3,
                },
                "node worker iter 2 is still live: refusing concurrent iter 3",
            ),
            (
                RejectReason::RunNotLive {
                    run_id: "run-1".into(),
                    status: RunStatus::Failed,
                    node_id: "worker".into(),
                    iter: 1,
                    kind: EventKind::NodeCompleted,
                },
                "run run-1 is Failed: cannot complete node worker iter 1 — resume the run first",
            ),
            (
                RejectReason::RunNotLive {
                    run_id: "run-1".into(),
                    status: RunStatus::Failed,
                    node_id: "worker".into(),
                    iter: 1,
                    kind: EventKind::NodeStarted,
                },
                "run run-1 is Failed: no scheduling on a non-running run — resume the run first",
            ),
            (
                RejectReason::IterationNotCompletable {
                    node_id: "worker".into(),
                    iter: 1,
                    status: NodeStatus::Stopped,
                },
                "node worker iter 1 is Stopped: cannot complete",
            ),
            (
                RejectReason::IterationNeverStarted {
                    node_id: "worker".into(),
                    iter: 1,
                },
                "node worker iter 1 was never started (no node_started event): cannot complete",
            ),
            (
                RejectReason::IterationAlreadyCompleted {
                    node_id: "worker".into(),
                    iter: 1,
                },
                "node worker iter 1 already completed: refusing to re-run it",
            ),
            (
                RejectReason::MissingNodeId {
                    kind: EventKind::NodeCompleted,
                },
                "completion event without node_id",
            ),
            (
                RejectReason::MissingNodeId {
                    kind: EventKind::NodeStarted,
                },
                "start event without node_id",
            ),
            (
                RejectReason::MissingNodeId {
                    kind: EventKind::NodeFailed,
                },
                "fail event without node_id",
            ),
            (
                RejectReason::MissingNodeId {
                    kind: EventKind::NodeStale,
                },
                "stale event without node_id",
            ),
        ];
        for (reason, want) in cases {
            assert_eq!(reason.to_string(), want);
        }
        // The wildcard-free constructor keeps this test honest as the enum grows.
        assert_eq!(every_reject_reason().len(), 6);
    }
}
