// start-node.jsx — Run-start pseudo-node + special inspector

function StartNode({ x, y, label = 'Run start', when = '4 m ago', runIdSlug, selected, onSelect, downstreamRunning }) {
  return (
    <div className={"start-node" + (selected ? " selected" : "")}
         style={{ left: x, top: y }}
         onClick={(e) => { e.stopPropagation(); onSelect && onSelect('__start'); }}>
      <span className="sn-play">
        <svg width="10" height="11" viewBox="0 0 10 11" fill="currentColor"><path d="M1 1.2v8.6a.5.5 0 0 0 .77.42l7.2-4.3a.5.5 0 0 0 0-.84L1.77.78A.5.5 0 0 0 1 1.2z"/></svg>
      </span>
      <span className="sn-main">
        <span className="sn-label">{label}</span>
        <span className="sn-meta">started {when} · {runIdSlug}</span>
      </span>
      <span className={"node-handle out" + (downstreamRunning ? ' active' : '')}/>
    </div>
  );
}

function StartEdges({ startX, startY, targetIds, nodes, runningSet }) {
  const NODE_H = 70;
  const sx = startX + 144;        // pill width
  const sy = startY + 28;          // pill mid
  return (
    <svg style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', pointerEvents: 'none' }}>
      {targetIds.map((id) => {
        const t = nodes.find(n => n.id === id);
        if (!t) return null;
        const tx = t.x, ty = t.y + NODE_H / 2;
        const dx = Math.max(40, Math.abs(tx - sx) * 0.5);
        const d = `M ${sx} ${sy} C ${sx + dx} ${sy}, ${tx - dx} ${ty}, ${tx} ${ty}`;
        const active = runningSet.has(id) || t.status === 'running' || t.status === 'done';
        return (
          <path key={'se-' + id} d={d}
            stroke={active ? "#10b981" : "#3a414c"}
            strokeWidth="1.5" fill="none"
            markerEnd={active ? "url(#arr-active)" : "url(#arr)"}/>
        );
      })}
    </svg>
  );
}

function StartInspector({ run, onOpenAsMarkdown }) {
  return (
    <div className="p-body">
      <div className="p-sect" style={{paddingBottom: 10}}>
        <div style={{display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4}}>
          <span className="sn-play" style={{width: 22, height: 22}}>
            <svg width="9" height="10" viewBox="0 0 10 11" fill="currentColor"><path d="M1 1.2v8.6a.5.5 0 0 0 .77.42l7.2-4.3a.5.5 0 0 0 0-.84L1.77.78A.5.5 0 0 0 1 1.2z"/></svg>
          </span>
          <div style={{flex: 1, minWidth: 0}}>
            <div style={{fontSize: 13, fontWeight: 600}}>Run start</div>
            <div style={{fontSize: 11, color: 'var(--fg-3)', marginTop: 2}} className="mono">runtime · pseudo-node</div>
            <div style={{fontSize: 10, color: 'var(--fg-4)', marginTop: 2}} className="mono">__start</div>
          </div>
          <span className="badge">runtime</span>
        </div>
        <div style={{fontSize: 11, color: 'var(--fg-4)', marginTop: 6, lineHeight: 1.5}}>
          The user input that triggered this run. Generated by the runtime — it is not in <span className="mono" style={{color: 'var(--fg-3)'}}>{run.pipeline}.yaml</span>.
        </div>
      </div>

      <div className="p-sect" style={{flex: 1, display: 'flex', flexDirection: 'column'}}>
        <SectionHead title="Submitted input"/>
        <div className="prompt-block" style={{flex: 1, maxHeight: 'none', whiteSpace: 'pre-wrap'}}>
{`# Implement search filter for archived projects

We currently show all projects in the library view. Add a toggle
that filters out archived projects (deletedAt != null) and persists
the user preference in localStorage.

## Constraints
- Don't break the existing parent/child filter
- Tests must cover both the new behavior and regressions
- Follow the existing zustand store pattern in src/state/library.ts

## Reference
- https://github.com/acme/pdo/issues/142
- See the related spike from last week: src/filters/__spike__/`}
        </div>
        <div style={{display: 'flex', justifyContent: 'flex-end', marginTop: 8}}>
          <a className="open-link" style={{cursor: 'pointer'}} onClick={onOpenAsMarkdown}>
            View as markdown ↗
          </a>
        </div>
      </div>
    </div>
  );
}

window.StartNode = StartNode;
window.StartEdges = StartEdges;
window.StartInspector = StartInspector;
